name: Build MinecraftForge

on:
  workflow_dispatch:
    paths:
      - 'MinecraftForge/**'

jobs:
  build:
    runs-on: windows-latest
    name: Build MinecraftForge Windows x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        architecture: 'x64'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.4'

    - name: Build with Gradle
      shell: cmd
      run: |
        cd MinecraftForge
        if not exist "gradlew.bat" powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/gradle/gradle/master/gradlew.bat', 'gradlew.bat')"
        if not exist "gradle/wrapper/gradle-wrapper.jar" mkdir gradle\wrapper & powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/gradle/gradle-wrapper/master/gradle/wrapper/gradle-wrapper.jar', 'gradle/wrapper/gradle-wrapper.jar')"
        gradlew.bat --version
        gradlew.bat setupDecompWorkspace --max-workers 1
        gradlew.bat build
      env:
        JAVA_OPTS: "-Xmx4G -Xms1G"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: forge-windows-x64
        path: MinecraftForge/build/libs/*.jar
        retention-days: 7
