name: Build OpenJDK for Windows

on:
  workflow_dispatch:
    paths:
      - 'OpenJDK/**'

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build OpenJDK for Windows x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lf-line-endings: true
        fetch-depth: 0  # 完全な履歴を取得

    # サブモジュールの設定がない場合は、直接OpenJDKをクローン
    - name: Clone OpenJDK
      shell: cmd
      run: |
        git clone https://github.com/openjdk/jdk.git OpenJDK
        cd OpenJDK
        git checkout jdk-17+35

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.3

    - name: Install Cygwin
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: >-
          make gcc-core gcc-g++ zip unzip autoconf m4
          perl libpng-devel libiconv-devel file findutils
          tar cpio wget gawk

    - name: Setup Boot JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        architecture: 'x64'

    - name: Prepare Build Environment
      shell: bash
      run: |
        OPENJDK_DIR="$(cygpath -u "$(pwd)/OpenJDK")"
        echo "OPENJDK_DIR=$OPENJDK_DIR" >> $GITHUB_ENV
        echo "PATH=/usr/bin:$PATH" >> $GITHUB_ENV
        echo "JAVA_HOME=$(cygpath -u "$JAVA_HOME")" >> $GITHUB_ENV

    - name: Build OpenJDK
      uses: ./OpenJDK/.github/actions/do-build
      with:
        make-target: 'images'
        platform: 'windows-x64'
        debug-suffix: ''

    - name: Upload Built JDK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: jdk-windows-x64
        path: |
          OpenJDK/build/*/images/jdk
          OpenJDK/build/*/images/jre
        retention-days: 7
