name: Build OpenJDK for Windows

on:
  workflow_dispatch:
    paths:
      - 'OpenJDK/**'

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build OpenJDK for Windows x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.3

    - name: Install Cygwin
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: make gcc-core gcc-g++ zip unzip autoconf m4 perl libpng-devel libiconv-devel

    - name: Setup Boot JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        architecture: 'x64'

    - name: Configure and Build
      shell: bash
      run: |
        cd OpenJDK
        export PATH="/usr/bin:$PATH"
        export JAVA_HOME_BACKUP=$JAVA_HOME
        export JAVA_HOME=$(cygpath -u "$JAVA_HOME_BACKUP")
        bash configure --with-boot-jdk=$JAVA_HOME --with-target-bits=64 --disable-warnings-as-errors
        make images
      env:
        JAVA_OPTS: "-Xmx4G -Xms1G"
