name: Build MinecraftForge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build MinecraftForge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: |
        ./gradlew setupDecompWorkspace
        ./gradlew build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: forge-artifacts
        path: build/libs/*.jar
