name: Build OpenJDK for Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build OpenJDK for Windows x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.3

    - name: Install Cygwin
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: make gcc-core gcc-g++ zip unzip autoconf

    - name: Setup Boot JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Configure and Build
      uses: ./.github/actions/do-build
      with:
        make-target: 'images'
        platform: 'windows-x64'
        debug-suffix: ''
